name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive

          - name: Test internet access for Buildroot downloads
            run: |
              echo "Checking if pkgconf tarball can be downloaded..."
              wget https://distfiles.dereferenced.org/pkgconf/pkgconf-2.3.0.tar.xz -O /tmp/pkgconf-test.tar.xz

          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
              FORCE_UNSAFE_CONFIGURE: 1 #added this line
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
